#!/usr/bin/env python3
"""Generate the XcodeGen spec used to build DoopEditor's distributable XCFrameworks.

The spec is derived from `Package.swift` and `Package.resolved` so it cannot drift from the
source build: grammar packages are pinned to the exact revisions SwiftPM resolved, and the
product list comes from the `CodeEditLanguages` target's dependencies.

Run via `Scripts/build-xcframeworks.sh`, which resolves the package first (the third-party
framework targets build from `.build/checkouts`).
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKOUTS = os.path.join(ROOT, ".build", "checkouts")
OUT_DIR = os.path.join(ROOT, "BinaryDistribution")
OUT = os.path.join(OUT_DIR, "project.yml")

# Every module that has to ship. A module ships when it appears in a public `.swiftinterface`
# (checked by Scripts/check-interface-imports.sh) or when one of our frameworks links it.
# Everything else -- the 40 grammars, DequeModule, _RopeModule -- is absorbed as a static
# library into the framework that uses it and stays invisible to consumers.
OUR_MODULES = ["CodeEditTextView", "CodeEditLanguages", "CodeEditSourceEditor"]
DEP_MODULES = ["Internal", "Rearrange", "TextStory", "TextFormation",
               "TreeSitter", "SwiftTreeSitter", "CodeEditTextViewObjC"]
ALL_MODULES = DEP_MODULES + OUR_MODULES


def read(path):
    with open(os.path.join(ROOT, path)) as handle:
        return handle.read()


def grammar_products():
    """(product, package identity) for each tree-sitter grammar the languages target links."""
    manifest = read("Package.swift")
    target = manifest.split("// MARK: - CodeEditLanguages", 1)[1]
    target = target.split("// MARK: - CodeEditSourceEditor", 1)[0]
    target = target.split("path:", 1)[0]
    pairs = re.findall(r'\.product\(name: "(\w+)", package: "([\w.-]+)"\)', target)
    return [(product, package) for product, package in pairs if package != "swift-tree-sitter"]


def resolved_revisions():
    """Pin every package to the revision SwiftPM actually resolved, so the binary matches source."""
    pins = json.loads(read("Package.resolved"))["pins"]
    return {pin["identity"]: (pin["location"], pin["state"]["revision"]) for pin in pins}


def language_resources():
    """The tree-sitter query directories, copied as folder references to preserve structure."""
    base = os.path.join(ROOT, "CodeEditLanguages", "Sources", "CodeEditLanguages", "Resources")
    return sorted(name for name in os.listdir(base)
                  if os.path.isdir(os.path.join(base, name)))


def checkout(*parts):
    path = os.path.join(CHECKOUTS, *parts)
    if not os.path.isdir(path):
        sys.exit("missing checkout: %s\nRun `swift package resolve` first." % path)
    return os.path.relpath(path, OUT_DIR)


def local(*parts):
    return os.path.relpath(os.path.join(ROOT, *parts), OUT_DIR)


def settings_block(extra=()):
    """Per-target settings.

    SKIP_INSTALL has to be set per target: XcodeGen writes `SKIP_INSTALL = YES` at the target
    level for framework targets, which overrides the project-level value, and an archive with
    SKIP_INSTALL on contains no framework to turn into an XCFramework.

    These belong here rather than on the xcodebuild command line, because command-line settings
    also apply to the SwiftPM dependencies -- and swift-collections does not compile with
    library evolution enabled.
    """
    lines = ["    settings:", "      base:", "        SKIP_INSTALL: NO"]
    for key, value in extra:
        lines.append("        %s: %s" % (key, value))
    return lines


def main():
    grammars = grammar_products()
    revisions = resolved_revisions()
    resources = language_resources()

    lines = []
    add = lines.append

    add("# Generated by Scripts/generate-binary-project.py -- do not edit by hand.")
    add("name: DoopEditorBinary")
    add("options:")
    add("  deploymentTarget: { macOS: \"13.0\" }")
    add("  createIntermediateGroups: true")
    add("  defaultConfig: Release")
    add("")
    add("configs:")
    add("  Release: release")
    add("")
    add("settings:")
    add("  base:")
    # BUILD_LIBRARY_FOR_DISTRIBUTION is what emits the .swiftinterface that makes the binaries
    # usable from a different compiler than the one that built them.
    add("    BUILD_LIBRARY_FOR_DISTRIBUTION: YES")
    add("    SKIP_INSTALL: NO")
    add("    DYLIB_INSTALL_NAME_BASE: \"@rpath\"")
    add("    MACOSX_DEPLOYMENT_TARGET: \"13.0\"")
    add("    ARCHS: \"arm64 x86_64\"")
    add("    ONLY_ACTIVE_ARCH: NO")
    add("    SWIFT_VERSION: \"5.10\"")
    add("    DEFINES_MODULE: YES")
    add("    CODE_SIGN_IDENTITY: \"\"")
    add("    CODE_SIGNING_REQUIRED: NO")
    add("    CODE_SIGNING_ALLOWED: NO")
    add("    SWIFT_INSTALL_OBJC_HEADER: NO")
    add("")

    add("packages:")
    for _, package in sorted(set((p, k) for p, k in grammars), key=lambda pair: pair[1]):
        location, revision = revisions[package]
        add("  %s:" % package)
        add("    url: %s" % location)
        add("    revision: %s" % revision)
    location, revision = revisions["swift-collections"]
    add("  swift-collections:")
    add("    url: %s" % location)
    add("    revision: %s" % revision)
    add("")

    add("targets:")

    # --- dependency layer -------------------------------------------------------------------
    # TextStory re-exports TSYTextStorage from its `Internal` ObjC target through a public
    # typealias, so `Internal` lands in TextStory's interface and has to ship under that name.
    add("  Internal:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % checkout("TextStory", "Sources", "Internal"))
    add("        headerVisibility: public")
    add("      - path: Support/Internal.h")
    add("        headerVisibility: public")
    lines.extend(settings_block())
    add("")

    add("  Rearrange:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % checkout("Rearrange", "Sources", "Rearrange"))
    add("        excludes: [\"Documentation.docc\"]")
    lines.extend(settings_block())
    add("")

    add("  TextStory:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % checkout("TextStory", "Sources", "TextStory"))
    add("        excludes: [\"Documentation.docc\"]")
    add("    dependencies:")
    add("      - target: Internal")
    add("      - target: Rearrange")
    lines.extend(settings_block())
    add("")

    add("  TextFormation:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % checkout("TextFormation", "Sources", "TextFormation"))
    add("        excludes: [\"Documentation.docc\"]")
    add("    dependencies:")
    add("      - target: TextStory")
    add("      - target: Rearrange")
    lines.extend(settings_block())
    add("")

    # Mirrors the tree-sitter package's own C target settings (path lib, sources src,
    # public headers include, and the POSIX feature defines it needs).
    add("  TreeSitter:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % checkout("tree-sitter", "lib", "src"))
    add("        excludes: [\"lib.c\", \"unicode/ICU_SHA\", \"unicode/README.md\", \"unicode/LICENSE\", \"wasm/stdlib-symbols.txt\"]")
    add("        headerVisibility: project")
    add("      - path: %s" % checkout("tree-sitter", "lib", "include"))
    add("        headerVisibility: public")
    add("      - path: Support/TreeSitter.h")
    add("        headerVisibility: public")
    lines.extend(settings_block([
        ("GCC_C_LANGUAGE_STANDARD", "c11"),
        ("GCC_PREPROCESSOR_DEFINITIONS",
         '"$(inherited) _POSIX_C_SOURCE=200112L _DEFAULT_SOURCE=1 _DARWIN_C_SOURCE=1"'),
        ("HEADER_SEARCH_PATHS", '"$(inherited) %s %s"' % (
            checkout("tree-sitter", "lib", "src"),
            checkout("tree-sitter", "lib", "include"))),
    ]))
    add("")

    add("  SwiftTreeSitter:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % checkout("swift-tree-sitter", "Sources", "SwiftTreeSitter"))
    add("        excludes: [\"Documentation.docc\"]")
    add("    dependencies:")
    add("      - target: TreeSitter")
    lines.extend(settings_block())
    add("")

    # Only linked, never named in an interface -- but it still has to ship, because both
    # CodeEditTextView and CodeEditSourceEditor link against it.
    add("  CodeEditTextViewObjC:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % local("CodeEditTextView", "Sources", "CodeEditTextViewObjC"))
    add("        excludes: [\"include/module.modulemap\"]")
    add("        headerVisibility: public")
    add("      - path: Support/CodeEditTextViewObjC.h")
    add("        headerVisibility: public")
    lines.extend(settings_block())
    add("")

    # --- our modules ------------------------------------------------------------------------
    # SWIFT_PACKAGE_NAME keeps the `package`-access declarations these modules share resolvable
    # across the framework boundary; AccessLevelOnImport enables the `internal import`s that
    # keep the grammars out of the public interfaces.
    our_settings = settings_block([
        ("SWIFT_PACKAGE_NAME", "DoopEditor"),
        ("OTHER_SWIFT_FLAGS",
         '"$(inherited) -enable-experimental-feature AccessLevelOnImport"'),
    ])

    add("  CodeEditTextView:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % local("CodeEditTextView", "Sources", "CodeEditTextView"))
    add("        excludes: [\"Documentation.docc\"]")
    add("    dependencies:")
    add("      - target: TextStory")
    add("      - target: CodeEditTextViewObjC")
    add("      - package: swift-collections")
    add("        product: DequeModule")
    lines.extend(our_settings)
    add("")

    add("  CodeEditLanguages:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % local("CodeEditLanguages", "Sources", "CodeEditLanguages"))
    add("        excludes: [\"Documentation.docc\", \"Resources\"]")
    for name in resources:
        # Folder references, so `Resources/tree-sitter-<lang>/<query>.scm` keeps the layout
        # CodeLanguage.queryURL(for:) expects inside the framework bundle.
        add("      - path: %s" % local("CodeEditLanguages", "Sources", "CodeEditLanguages",
                                       "Resources", name))
        add("        type: folder")
        add("        buildPhase: resources")
    add("    dependencies:")
    add("      - target: SwiftTreeSitter")
    for product, package in grammars:
        add("      - package: %s" % package)
        add("        product: %s" % product)
    lines.extend(our_settings)
    add("        OTHER_LDFLAGS: \"$(inherited) -lc++\"")
    add("")

    add("  CodeEditSourceEditor:")
    add("    type: framework")
    add("    platform: macOS")
    add("    sources:")
    add("      - path: %s" % local("CodeEditSourceEditor", "Sources", "CodeEditSourceEditor"))
    add("        excludes: [\"Documentation.docc\"]")
    add("    dependencies:")
    add("      - target: CodeEditTextView")
    add("      - target: CodeEditLanguages")
    add("      - target: TextFormation")
    add("      - target: CodeEditTextViewObjC")
    add("      - package: swift-collections")
    add("        product: _RopeModule")
    lines.extend(our_settings)
    add("")

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    print("wrote %s (%d modules, %d grammar products)" % (
        os.path.relpath(OUT, ROOT), len(ALL_MODULES), len(grammars)))


if __name__ == "__main__":
    main()
