#!/usr/bin/env python3
"""Generate the doop-editor-binary package from a completed xcframework build.

The XCFrameworks are attached to the doop-editor GitHub release for a version; the package
that points at them lives in its own repository, doop-editor-binary, tagged with the same
version. Keeping it out of this repo means each repository has exactly one tag per version --
SwiftPM strips a leading `v` when reading tags, so a `v0.9.0` and a `0.9.0` in one repo are two
tags for the same version, and it silently resolves whichever it prefers.

`.binaryTarget` can't declare dependencies, so each product lists every binary target it needs
transitively -- that's what makes SwiftPM link and embed the whole set when a consumer depends
on the product.

Usage: Scripts/generate-binary-manifest.py <vX.Y.Z> [--source-repo owner/name]
                                                   [--binary-repo owner/name]
Reads build/xcframeworks/binary-targets.txt (module, checksum and direct dependencies, written
by Scripts/build-xcframeworks.sh) and writes build/binary-package/{Package.swift,README.md}.
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKSUMS = os.path.join(ROOT, "build", "xcframeworks", "binary-targets.txt")
OUT_DIR = os.path.join(ROOT, "build", "binary-package")

# Matches the tags this repo already uses. The release assets live under the tag name, so a
# version without the `v` would produce download URLs that 404.
VERSION = re.compile(r"^v\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$")

# Each product's roots. The rest of its target list is the transitive closure of these over
# the link graph recorded by Scripts/build-xcframeworks.sh -- `.binaryTarget` can't declare
# dependencies, so a product has to name every framework it needs, and hand-maintaining that
# list goes stale the moment Xcode changes how it links a SwiftPM dependency.
PRODUCT_ROOTS = {
    "CodeEditSourceEditor": ["CodeEditSourceEditor"],
    "CodeEditTextView": ["CodeEditTextView"],
    "CodeEditLanguages": ["CodeEditLanguages"],
}


def closure(roots, deps):
    """Every framework reachable from `roots`, in a stable order."""
    ordered = []
    queue = list(roots)
    while queue:
        name = queue.pop(0)
        if name in ordered:
            continue
        ordered.append(name)
        queue.extend(deps.get(name, []))
    return ordered


def read_build():
    if not os.path.exists(CHECKSUMS):
        sys.exit("missing %s -- run Scripts/build-xcframeworks.sh first" % CHECKSUMS)

    checksums = {}
    deps = {}
    order = []
    with open(CHECKSUMS) as handle:
        for line in handle:
            if not line.strip():
                continue
            module, checksum, dependencies = line.split()
            checksums[module] = checksum
            deps[module] = [] if dependencies == "-" else dependencies.split(",")
            order.append(module)
    return checksums, deps, order


def manifest(version, source_repo, checksums, products, order):
    base = "https://github.com/%s/releases/download/%s" % (source_repo, version)

    lines = [
        "// swift-tools-version: 5.9",
        "//",
        "// Prebuilt DoopEditor %s." % version,
        "//",
        "// Generated by Scripts/generate-binary-manifest.py in %s -- do not edit by hand."
        % source_repo,
        "// The XCFrameworks are attached to the matching release there.",
        "//",
        "// `.binaryTarget` cannot declare dependencies, so each product lists the whole set of",
        "// frameworks it needs transitively.",
        "import PackageDescription",
        "",
        "let package = Package(",
        "    name: \"DoopEditor\",",
        "    platforms: [.macOS(.v13)],",
        "    products: [",
    ]
    for product in PRODUCT_ROOTS:
        lines.append("        .library(")
        lines.append("            name: \"%s\"," % product)
        lines.append("            targets: [")
        for target in products[product]:
            lines.append("                \"%s\"," % target)
        lines.append("            ]")
        lines.append("        ),")
    lines.append("    ],")
    lines.append("    targets: [")
    for module in order:
        lines.append("        .binaryTarget(")
        lines.append("            name: \"%s\"," % module)
        lines.append("            url: \"%s/%s.xcframework.zip\"," % (base, module))
        lines.append("            checksum: \"%s\"" % checksums[module])
        lines.append("        ),")
    lines.append("    ]")
    lines.append(")")
    return "\n".join(lines) + "\n"


def readme(version, source_repo, binary_repo, order):
    identity = binary_repo.split("/")[-1]
    source_identity = source_repo.split("/")[-1]
    supporting = "\n".join("- `%s`" % module for module in order
                           if module not in PRODUCT_ROOTS)

    return """# DoopEditor (prebuilt)

Prebuilt macOS XCFrameworks of [%(source_repo)s](https://github.com/%(source_repo)s). Depending
on this package instead of the source one skips cloning and compiling the 40+ tree-sitter
grammar packages, which are statically linked into `CodeEditLanguages`.

This repository holds only the generated `Package.swift`. The frameworks themselves are
attached to the [%(version)s release](https://github.com/%(source_repo)s/releases/tag/%(version)s)
of the source repository, and each tag here matches a tag there.

```swift
dependencies: [
    .package(url: "https://github.com/%(binary_repo)s.git", from: "%(semver)s"),
],
```

The products are the same as the source package's -- `CodeEditSourceEditor`,
`CodeEditTextView` and `CodeEditLanguages` -- but SwiftPM names a package after its repository,
so switching from source to binary changes the `package:` in each product reference:

```swift
.product(name: "CodeEditSourceEditor", package: "%(identity)s"),  // was "%(source_identity)s"
```

These frameworks ship too, because their types appear in the three modules' public interfaces
or the modules load them at runtime:

%(supporting)s

Generated for %(version)s by `Scripts/generate-binary-manifest.py` in the source repository --
do not edit by hand; changes here are overwritten by the next release.
""" % {
        "source_repo": source_repo,
        "binary_repo": binary_repo,
        "version": version,
        "semver": version.removeprefix("v"),
        "identity": identity,
        "source_identity": source_identity,
        "supporting": supporting,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("version", help="release tag, e.g. v0.9.0")
    parser.add_argument("--source-repo", default="matiaskorhonen/doop-editor",
                        help="repository whose release holds the XCFramework zips")
    parser.add_argument("--binary-repo", default="matiaskorhonen/doop-editor-binary",
                        help="repository the generated package is published to")
    args = parser.parse_args()

    if not VERSION.match(args.version):
        sys.exit("version must be a tag like v0.9.0, got %r" % args.version)

    checksums, deps, order = read_build()
    products = {name: closure(roots, deps) for name, roots in PRODUCT_ROOTS.items()}

    missing = {m for names in products.values() for m in names} - set(checksums)
    if missing:
        sys.exit("no checksum for: %s" % ", ".join(sorted(missing)))

    os.makedirs(OUT_DIR, exist_ok=True)
    outputs = {
        "Package.swift": manifest(args.version, args.source_repo, checksums, products, order),
        "README.md": readme(args.version, args.source_repo, args.binary_repo, order),
    }
    for name, contents in outputs.items():
        path = os.path.join(OUT_DIR, name)
        with open(path, "w") as handle:
            handle.write(contents)
        print("wrote %s" % os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
