#!/usr/bin/env python3
"""Generate the Package.swift for the `binary` branch from a completed xcframework build.

`.binaryTarget` can't declare dependencies, so each product lists every binary target it needs
transitively -- that's what makes SwiftPM link and embed the whole set when a consumer depends
on the product.

Usage: Scripts/generate-binary-manifest.py <version> [--repo owner/name]
Reads build/xcframeworks/binary-targets.txt (module + checksum, written by
Scripts/build-xcframeworks.sh) and writes build/binary-branch/Package.swift.
"""

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKSUMS = os.path.join(ROOT, "build", "xcframeworks", "binary-targets.txt")
OUT_DIR = os.path.join(ROOT, "build", "binary-branch")

# Each product's roots. The rest of its target list is the transitive closure of these over
# the link graph recorded by Scripts/build-xcframeworks.sh -- `.binaryTarget` can't declare
# dependencies, so a product has to name every framework it needs, and hand-maintaining that
# list goes stale the moment Xcode changes how it links a SwiftPM dependency.
PRODUCT_ROOTS = {
    "CodeEditSourceEditor": ["CodeEditSourceEditor"],
    "CodeEditTextView": ["CodeEditTextView"],
    "CodeEditLanguages": ["CodeEditLanguages"],
}


def closure(roots, deps):
    """Every framework reachable from `roots`, in a stable order."""
    ordered = []
    queue = list(roots)
    while queue:
        name = queue.pop(0)
        if name in ordered:
            continue
        ordered.append(name)
        queue.extend(deps.get(name, []))
    return ordered


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("version")
    parser.add_argument("--repo", default="matiaskorhonen/doop-editor")
    args = parser.parse_args()

    if not os.path.exists(CHECKSUMS):
        sys.exit("missing %s -- run Scripts/build-xcframeworks.sh first" % CHECKSUMS)

    checksums = {}
    deps = {}
    order = []
    with open(CHECKSUMS) as handle:
        for line in handle:
            if not line.strip():
                continue
            module, checksum, dependencies = line.split()
            checksums[module] = checksum
            deps[module] = [] if dependencies == "-" else dependencies.split(",")
            order.append(module)

    products = {name: closure(roots, deps) for name, roots in PRODUCT_ROOTS.items()}

    missing = {m for names in products.values() for m in names} - set(checksums)
    if missing:
        sys.exit("no checksum for: %s" % ", ".join(sorted(missing)))

    base = "https://github.com/%s/releases/download/%s" % (args.repo, args.version)

    lines = [
        "// swift-tools-version: 5.9",
        "//",
        "// Prebuilt DoopEditor %s." % args.version,
        "//",
        "// Generated by Scripts/generate-binary-manifest.py on the `binary` branch -- do not",
        "// edit by hand. The source package lives on `main`; this manifest only wires up the",
        "// XCFrameworks attached to the matching GitHub release.",
        "//",
        "// `.binaryTarget` cannot declare dependencies, so each product lists the whole set of",
        "// frameworks it needs transitively.",
        "import PackageDescription",
        "",
        "let package = Package(",
        "    name: \"DoopEditor\",",
        "    platforms: [.macOS(.v13)],",
        "    products: [",
    ]
    for product in ("CodeEditSourceEditor", "CodeEditTextView", "CodeEditLanguages"):
        lines.append("        .library(")
        lines.append("            name: \"%s\"," % product)
        lines.append("            targets: [")
        for target in products[product]:
            lines.append("                \"%s\"," % target)
        lines.append("            ]")
        lines.append("        ),")
    lines.append("    ],")
    lines.append("    targets: [")
    for module in order:
        lines.append("        .binaryTarget(")
        lines.append("            name: \"%s\"," % module)
        lines.append("            url: \"%s/%s.xcframework.zip\"," % (base, module))
        lines.append("            checksum: \"%s\"" % checksums[module])
        lines.append("        ),")
    lines.append("    ]")
    lines.append(")")

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, "Package.swift")
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")

    readme = os.path.join(OUT_DIR, "README.md")
    with open(readme, "w") as handle:
        handle.write("""# DoopEditor (prebuilt)

This branch carries only the SwiftPM manifest for the **prebuilt** DoopEditor XCFrameworks. The
sources live on [`main`](https://github.com/%s/tree/main); see `UPSTREAM.md` there.

Consume it the usual way -- git tags are branch-independent, so a version tag resolves to this
manifest rather than the source one:

```swift
.package(url: "https://github.com/%s.git", from: "%s")
```

Products are named exactly as on `main` (`CodeEditSourceEditor`, `CodeEditTextView`,
`CodeEditLanguages`), so switching between source and binary needs no changes in the consumer's
target dependencies.

These also ship, because their types appear in the three modules' public interfaces or they
are linked by them:

%s

The tree-sitter grammars are *not* separate frameworks -- they are statically linked into
`CodeEditLanguages`, which is the point of the binary distribution.

Generated for %s -- do not edit by hand.
""" % (args.repo, args.repo, args.version.lstrip("v"),
       "\n".join("- `%s`" % m for m in order
                  if m not in ("CodeEditSourceEditor", "CodeEditTextView",
                               "CodeEditLanguages")),
       args.version))

    print("wrote %s" % os.path.relpath(path, ROOT))
    print("wrote %s" % os.path.relpath(readme, ROOT))


if __name__ == "__main__":
    main()
