#!/bin/bash
#
# Verify the built XCFrameworks from a consumer's point of view.
#
# Builds a throwaway SwiftPM package that depends only on the XCFrameworks (no tree-sitter
# grammar packages, no source dependencies) and runs it. This checks the two things that
# can't be seen from the build logs:
#
#   1. the shipped .swiftinterface files are self-contained -- if anything absorbed leaked in,
#      resolving this package fails because the grammar modules aren't there;
#   2. CodeEditLanguages finds its .scm queries inside the framework bundle at runtime, which
#      is what `Bundle.codeEditLanguages` replaced `Bundle.module` for.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
FRAMEWORKS="$ROOT/build/xcframeworks"
# SwiftPM rejects a binaryTarget path outside the package root, so the frameworks are cloned
# into the throwaway package rather than referenced where they were built. On APFS `cp -c`
# clones the blocks, so this costs no real space or time.
WORK="$ROOT/build/consumer-check"

# Take the shipped set from the build rather than repeating it here, so this can't end up
# testing a different set of frameworks than the one that would be released.
TARGETS="$FRAMEWORKS/binary-targets.txt"
if [ ! -f "$TARGETS" ]; then
    echo "error: $TARGETS not found -- run Scripts/build-xcframeworks.sh first" >&2
    exit 1
fi
MODULES=($(cut -d' ' -f1 "$TARGETS"))

for module in "${MODULES[@]}"; do
    if [ ! -d "$FRAMEWORKS/$module.xcframework" ]; then
        echo "error: $FRAMEWORKS/$module.xcframework not found -- run Scripts/build-xcframeworks.sh" >&2
        exit 1
    fi
done

rm -rf "$WORK"
mkdir -p "$WORK/Sources/Consumer" "$WORK/Frameworks"

for module in "${MODULES[@]}"; do
    cp -Rc "$FRAMEWORKS/$module.xcframework" "$WORK/Frameworks/" 2>/dev/null \
        || cp -R "$FRAMEWORKS/$module.xcframework" "$WORK/Frameworks/"
done

{
    echo '// swift-tools-version: 5.9'
    echo '// Generated by Scripts/verify-binary-consumption.sh'
    echo 'import PackageDescription'
    echo ''
    echo 'let package = Package('
    echo '    name: "Consumer",'
    echo '    platforms: [.macOS(.v13)],'
    echo '    targets: ['
    for module in "${MODULES[@]}"; do
        echo "        .binaryTarget(name: \"$module\", path: \"Frameworks/$module.xcframework\"),"
    done
    echo '        .executableTarget('
    echo '            name: "Consumer",'
    echo '            dependencies: ['
    for module in "${MODULES[@]}"; do
        echo "                \"$module\","
    done
    echo '            ]'
    echo '        ),'
    echo '    ]'
    echo ')'
} > "$WORK/Package.swift"

cat > "$WORK/Sources/Consumer/main.swift" <<'SWIFT'
import Foundation
import CodeEditLanguages
import CodeEditSourceEditor
import CodeEditTextView
import SwiftTreeSitter

// Exercising the public API is what forces the compiler to read the shipped .swiftinterface
// files, so a leaked import shows up here as a resolution failure.
let textView = TextView(string: "let x = 1")
precondition(textView.string == "let x = 1", "TextView did not round-trip its string")

var failures: [String] = []
for language in [CodeLanguage.swift, .python, .rust, .json, .markdown, .go] {
    guard let url = language.queryURL else {
        failures.append("\(language.id.rawValue): no query URL")
        continue
    }
    guard FileManager.default.fileExists(atPath: url.path) else {
        failures.append("\(language.id.rawValue): missing \(url.path)")
        continue
    }
    guard let tsLanguage = language.language else {
        failures.append("\(language.id.rawValue): no tree-sitter language")
        continue
    }
    // Compiling the query proves both the grammar (statically linked into the framework) and
    // its .scm resource (copied into the framework bundle) actually made it through.
    do {
        _ = try Query(language: tsLanguage, url: url)
    } catch {
        failures.append("\(language.id.rawValue): query failed to compile: \(error)")
    }
}

if failures.isEmpty {
    print("binary consumption OK: interfaces resolve, grammars link, queries load")
} else {
    for failure in failures { print("FAIL \(failure)") }
    exit(1)
}
SWIFT

echo "==> Building the consumer package"
(cd "$WORK" && swift build 2>&1 | tail -20)

echo "==> Running the consumer"
binary=$(cd "$WORK" && swift build --show-bin-path)/Consumer
# SwiftPM doesn't embed binary frameworks into a plain executable the way Xcode does, so point
# dyld at them directly. Xcode consumers get this via Embed & Sign automatically.
DYLD_FRAMEWORK_PATH="$(cd "$WORK" && swift build --show-bin-path)" "$binary"
