#!/bin/bash
#
# Verify a release from a consumer's point of view: the XCFramework, and the generated
# doop-editor-binary package that points at it.
#
# Builds a throwaway executable that depends on the generated package and runs it. That checks what
# cannot be seen from the build logs:
#
#   1. the generated Package.swift is valid and the product lists every framework it needs. A
#      missing module fails the build, a missing dylib fails the launch;
#   2. the shipped .swiftinterface is self-contained -- if anything absorbed leaked in, building
#      fails, because none of the absorbed modules are there to import;
#   3. the .scm queries are found inside the framework bundle at runtime, which is what
#      `Bundle.codeEditLanguages` replaced `Bundle.module` for, and the grammars are linked in.
#
# The release's download URLs don't resolve until it is published, so the manifest is loaded as
# generated, and then built from a copy whose binary targets point at the local frameworks instead.
#
# Usage: Scripts/verify-binary-consumption.sh
# Run after Scripts/build-xcframeworks.sh and Scripts/generate-binary-manifest.swift.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
FRAMEWORKS="$ROOT/build/xcframeworks"
GENERATED="$ROOT/build/binary-package"
WORK="$ROOT/build/consumer-check"
# Named like the real repository, so product references read exactly as they do in a consumer.
PREBUILT="$WORK/doop-editor-binary"
CONSUMER="$WORK/Consumer"


TARGETS="$FRAMEWORKS/binary-targets.txt"
if [ ! -f "$TARGETS" ]; then
    echo "error: $TARGETS not found -- run Scripts/build-xcframeworks.sh first" >&2
    exit 1
fi
if [ ! -f "$GENERATED/Package.swift" ]; then
    echo "error: $GENERATED/Package.swift not found -- run Scripts/generate-binary-manifest.swift first" >&2
    exit 1
fi
MODULES=($(cut -d' ' -f1 "$TARGETS"))

for module in "${MODULES[@]}"; do
    if [ ! -d "$FRAMEWORKS/$module.xcframework" ]; then
        echo "error: $FRAMEWORKS/$module.xcframework not found -- run Scripts/build-xcframeworks.sh" >&2
        exit 1
    fi
done

rm -rf "$WORK"
mkdir -p "$PREBUILT/Frameworks"

echo "==> Loading the generated manifest"
# Exactly the file that will be published: its syntax, and the form of its URLs and checksums.
swift package --package-path "$GENERATED" --scratch-path "$WORK/manifest" dump-package > /dev/null

# SwiftPM rejects a binaryTarget path outside the package root, so the frameworks are cloned into
# the local copy rather than referenced where they were built. On APFS `cp -c` clones the blocks,
# so this costs no real space or time.
for module in "${MODULES[@]}"; do
    cp -Rc "$FRAMEWORKS/$module.xcframework" "$PREBUILT/Frameworks/" 2>/dev/null \
        || cp -R "$FRAMEWORKS/$module.xcframework" "$PREBUILT/Frameworks/"
done

# Only each binary target's url and checksum change; the products stay exactly as generated.
sed -E \
    -e 's|^([[:space:]]*)url: "https://[^"]*/([A-Za-z0-9_]+)\.xcframework\.zip",$|\1path: "Frameworks/\2.xcframework"|' \
    -e '/^[[:space:]]*checksum: "[0-9a-f]+"$/d' \
    "$GENERATED/Package.swift" > "$PREBUILT/Package.swift"

if [ "$(grep -c 'path: "Frameworks/' "$PREBUILT/Package.swift")" -ne "${#MODULES[@]}" ] \
    || grep -qE '^[[:space:]]*(url|checksum):' "$PREBUILT/Package.swift"; then
    echo "error: couldn't point the generated manifest's ${#MODULES[@]} binary targets at local frameworks" >&2
    echo "       -- has the form of its binaryTarget entries changed?" >&2
    exit 1
fi

mkdir -p "$CONSUMER"
cat > "$CONSUMER/Package.swift" <<'MANIFEST'
// swift-tools-version: 5.9
// Generated by Scripts/verify-binary-consumption.sh
import PackageDescription

let package = Package(
    name: "Consumer",
    platforms: [.macOS(.v13)],
    dependencies: [.package(path: "../doop-editor-binary")],
    targets: [
        .executableTarget(name: "CheckDoopEditor", dependencies: [
            .product(name: "DoopEditor", package: "doop-editor-binary"),
        ]),
    ]
)
MANIFEST

mkdir -p "$CONSUMER/Sources/CheckDoopEditor"

# Exercising the public API is what forces the compiler to read the shipped .swiftinterface, so a
# leaked import shows up as a build failure.
cat > "$CONSUMER/Sources/CheckDoopEditor/main.swift" <<'SWIFT'
import AppKit
import DoopEditor

// The former three modules' public API, all reachable from the one module.
let detected = CodeLanguage.detectLanguageFrom(url: URL(fileURLWithPath: "example.swift"))
precondition(detected.id == .swift, "language detection did not find Swift")
precondition(CodeLanguage.allLanguages.count > 30, "the language list is suspiciously short")

let behavior = SourceEditorConfiguration.Behavior(indentOption: .spaces(count: 2))
let state = SourceEditorState(findText: "let")
precondition(behavior.indentOption == .spaces(count: 2) && state.findText == "let",
             "configuration values did not round-trip")

let textView = TextView(string: "let x = 1")
precondition(textView.string == "let x = 1", "TextView did not round-trip its string")

// `isHighlightable` compiles the bundled query against the grammar, which proves both made it in:
// the grammar is linked statically into the framework, the `.scm` is a resource in its bundle.
var failures: [String] = []
for language in [CodeLanguage.swift, .python, .rust, .json, .markdown, .go] {
    guard language.queryURL != nil else {
        failures.append("\(language.id.rawValue): no query URL")
        continue
    }
    guard language.isHighlightable else {
        failures.append("\(language.id.rawValue): grammar or query missing")
        continue
    }
}

if failures.isEmpty {
    print("DoopEditor OK: the interface resolves, the framework loads, grammars link, queries compile")
} else {
    for failure in failures { print("FAIL \(failure)") }
    exit(1)
}
SWIFT

echo "==> Building and running the DoopEditor product"
(cd "$CONSUMER" && swift build --scratch-path "$WORK/scratch" --product CheckDoopEditor 2>&1 | tail -40)
bin="$(cd "$CONSUMER" && swift build --scratch-path "$WORK/scratch" --show-bin-path)"
# SwiftPM doesn't embed binary frameworks into a plain executable the way Xcode does, so point
# dyld at the one this build copied. Xcode consumers get this via Embed & Sign automatically.
DYLD_FRAMEWORK_PATH="$bin" "$bin/CheckDoopEditor"

echo "binary consumption OK: the generated package builds and runs"
