#!/bin/bash
#
# Verify a release from a consumer's point of view: the XCFrameworks, and the generated
# doop-editor-binary package that points at them.
#
# Builds throwaway executables that depend on the generated package -- one per product, each built
# on its own -- and runs them. That checks what can't be seen from the build logs:
#
#   1. the generated Package.swift is valid, and each product lists every framework it needs. A
#      product missing one fails to compile (a missing module) or to launch (a missing dylib);
#   2. the shipped .swiftinterface files are self-contained -- if anything absorbed leaked in,
#      building fails because the grammar modules aren't there;
#   3. CodeEditLanguages finds its .scm queries inside the framework bundle at runtime, which
#      is what `Bundle.codeEditLanguages` replaced `Bundle.module` for.
#
# The release's download URLs don't resolve until it is published, so the manifest is loaded as
# generated, and then built from a copy whose binary targets point at the local frameworks instead.
#
# Usage: Scripts/verify-binary-consumption.sh
# Run after Scripts/build-xcframeworks.sh and Scripts/generate-binary-manifest.swift.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
FRAMEWORKS="$ROOT/build/xcframeworks"
GENERATED="$ROOT/build/binary-package"
WORK="$ROOT/build/consumer-check"
# Named like the real repository, so product references read exactly as they do in a consumer.
PREBUILT="$WORK/doop-editor-binary"
CONSUMER="$WORK/Consumer"
PRODUCTS=(CodeEditTextView CodeEditLanguages CodeEditSourceEditor)

TARGETS="$FRAMEWORKS/binary-targets.txt"
if [ ! -f "$TARGETS" ]; then
    echo "error: $TARGETS not found -- run Scripts/build-xcframeworks.sh first" >&2
    exit 1
fi
if [ ! -f "$GENERATED/Package.swift" ]; then
    echo "error: $GENERATED/Package.swift not found -- run Scripts/generate-binary-manifest.swift first" >&2
    exit 1
fi
MODULES=($(cut -d' ' -f1 "$TARGETS"))

for module in "${MODULES[@]}"; do
    if [ ! -d "$FRAMEWORKS/$module.xcframework" ]; then
        echo "error: $FRAMEWORKS/$module.xcframework not found -- run Scripts/build-xcframeworks.sh" >&2
        exit 1
    fi
done

rm -rf "$WORK"
mkdir -p "$PREBUILT/Frameworks"

echo "==> Loading the generated manifest"
# Exactly the file that will be published: its syntax, and the form of its URLs and checksums.
swift package --package-path "$GENERATED" --scratch-path "$WORK/manifest" dump-package > /dev/null

# SwiftPM rejects a binaryTarget path outside the package root, so the frameworks are cloned into
# the local copy rather than referenced where they were built. On APFS `cp -c` clones the blocks,
# so this costs no real space or time.
for module in "${MODULES[@]}"; do
    cp -Rc "$FRAMEWORKS/$module.xcframework" "$PREBUILT/Frameworks/" 2>/dev/null \
        || cp -R "$FRAMEWORKS/$module.xcframework" "$PREBUILT/Frameworks/"
done

# Only each binary target's url and checksum change; the products stay exactly as generated.
sed -E \
    -e 's|^([[:space:]]*)url: "https://[^"]*/([A-Za-z0-9_]+)\.xcframework\.zip",$|\1path: "Frameworks/\2.xcframework"|' \
    -e '/^[[:space:]]*checksum: "[0-9a-f]+"$/d' \
    "$GENERATED/Package.swift" > "$PREBUILT/Package.swift"

if [ "$(grep -c 'path: "Frameworks/' "$PREBUILT/Package.swift")" -ne "${#MODULES[@]}" ] \
    || grep -qE '^[[:space:]]*(url|checksum):' "$PREBUILT/Package.swift"; then
    echo "error: couldn't point the generated manifest's ${#MODULES[@]} binary targets at local frameworks" >&2
    echo "       -- has the form of its binaryTarget entries changed?" >&2
    exit 1
fi

mkdir -p "$CONSUMER"
{
    echo '// swift-tools-version: 5.9'
    echo '// Generated by Scripts/verify-binary-consumption.sh'
    echo 'import PackageDescription'
    echo ''
    echo 'let package = Package('
    echo '    name: "Consumer",'
    echo '    platforms: [.macOS(.v13)],'
    echo '    dependencies: [.package(path: "../doop-editor-binary")],'
    echo '    targets: ['
    for product in "${PRODUCTS[@]}"; do
        echo "        .executableTarget(name: \"Check$product\", dependencies: ["
        echo "            .product(name: \"$product\", package: \"doop-editor-binary\"),"
        echo '        ]),'
    done
    echo '    ]'
    echo ')'
} > "$CONSUMER/Package.swift"

mkdir -p "$CONSUMER/Sources/CheckCodeEditTextView" \
    "$CONSUMER/Sources/CheckCodeEditLanguages" \
    "$CONSUMER/Sources/CheckCodeEditSourceEditor"

# Exercising the public API is what forces the compiler to read the shipped .swiftinterface files,
# so a leaked import shows up as a build failure. Each executable links every framework in its
# product, so launching it has dyld load that product's whole set.
cat > "$CONSUMER/Sources/CheckCodeEditTextView/main.swift" <<'SWIFT'
import CodeEditTextView

let textView = TextView(string: "let x = 1")
precondition(textView.string == "let x = 1", "TextView did not round-trip its string")
print("CodeEditTextView OK: the interface resolves and the frameworks load")
SWIFT

cat > "$CONSUMER/Sources/CheckCodeEditLanguages/main.swift" <<'SWIFT'
import Foundation
import CodeEditLanguages
import SwiftTreeSitter

var failures: [String] = []
for language in [CodeLanguage.swift, .python, .rust, .json, .markdown, .go] {
    guard let url = language.queryURL else {
        failures.append("\(language.id.rawValue): no query URL")
        continue
    }
    guard FileManager.default.fileExists(atPath: url.path) else {
        failures.append("\(language.id.rawValue): missing \(url.path)")
        continue
    }
    guard let tsLanguage = language.language else {
        failures.append("\(language.id.rawValue): no tree-sitter language")
        continue
    }
    // Compiling the query proves both the grammar (statically linked into the framework) and
    // its .scm resource (copied into the framework bundle) actually made it through.
    do {
        _ = try Query(language: tsLanguage, url: url)
    } catch {
        failures.append("\(language.id.rawValue): query failed to compile: \(error)")
    }
}

if failures.isEmpty {
    print("CodeEditLanguages OK: grammars link, queries load")
} else {
    for failure in failures { print("FAIL \(failure)") }
    exit(1)
}
SWIFT

cat > "$CONSUMER/Sources/CheckCodeEditSourceEditor/main.swift" <<'SWIFT'
import CodeEditSourceEditor
import CodeEditLanguages
import CodeEditTextView

let behavior = SourceEditorConfiguration.Behavior(indentOption: .spaces(count: 2))
let state = SourceEditorState(findText: "let")
precondition(behavior.indentOption == .spaces(count: 2) && state.findText == "let",
             "CodeEditSourceEditor values did not round-trip")
let language: CodeLanguage = .swift
print("CodeEditSourceEditor OK: the interface resolves and the frameworks load (\(language.id.rawValue))")
SWIFT

# Each product is built with its own scratch path, so its executable only finds the frameworks that
# product brought in -- not ones another product's build happened to copy alongside it.
for product in "${PRODUCTS[@]}"; do
    echo "==> Building and running the $product product on its own"
    scratch="$WORK/scratch-$product"
    (cd "$CONSUMER" && swift build --scratch-path "$scratch" --product "Check$product" 2>&1 | tail -40)
    bin="$(cd "$CONSUMER" && swift build --scratch-path "$scratch" --show-bin-path)"
    # SwiftPM doesn't embed binary frameworks into a plain executable the way Xcode does, so point
    # dyld at the ones this build copied. Xcode consumers get this via Embed & Sign automatically.
    DYLD_FRAMEWORK_PATH="$bin" "$bin/Check$product"
done

echo "binary consumption OK: the generated package builds and runs, product by product"
